INSERT INTO TB_CATEGORY (NAME) VALUES ('BOOKS');
INSERT INTO TB_CATEGORY (NAME) VALUES ('AUTOS');
INSERT INTO TB_CATEGORY (NAME) VALUES ('ELECTRONICS');
INSERT INTO TB_CATEGORY (NAME) VALUES ('COMPUTERS');