INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('BOOKS', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('AUTOS', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('ELECTRONICS', now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('COMPUTERS', now());